[workspace]
authors = ["Martin Schumann <mfs@mfs.name>"]
channels = []
name = "link4000"
platforms = ["linux-64", "win-64"]
version = "1.2.1"

[dependencies]
python = "3.13.*"
pyside6 = "*"
tomli-w = "*"

[target.win-64.dependencies]
pywin32 = "*"

[feature.test.dependencies]
pytest = "*"
pytest-cov = "*"

[feature.dev.dependencies]
snakeviz = "*"
py-spy = "*"
ruff = "*"
pixi-pycharm = "*"

[feature.default-channels]
channels = ["main", "services"]

[feature.forge-channels]
channels = ["conda-forge"]

[environments.default]
features = ["default-channels"]
solve-group = "anaconda"

[environments.test]
features = ["test", "default-channels"]
solve-group = "anaconda"

[environments.dev]
features = ["test", "dev", "forge-channels"]
solve-group = "forge"