"""Multi-store "library" that aggregates all configured Link4000 stores.

The :class:`StoreRegistry` is the central access point for link operations
across every configured store. It is built from the store configuration
returned by :func:`link4000.utils.config.get_stores` and exposes a
store-name-keyed view over the underlying :class:`LinkStore` instances.
"""

from typing import Dict, List, Optional, Tuple

from link4000.data.link_store import LinkStore
from link4000.models.link import Link
from link4000.utils.config import get_links_file_path, get_stores


class StoreRegistry:
    """Aggregates all configured link stores into a single library.

    Each configured store is instantiated as a :class:`LinkStore` and kept in
    a ``name -> LinkStore`` mapping. The registry routes link CRUD operations
    to the appropriate store and aggregates read operations across all stores,
    tagging each returned link with the name of the store that owns it.

    Attributes:
        _stores: Mapping of store name to its :class:`LinkStore` instance.
    """

    def __init__(self) -> None:
        """Build the registry from the store configuration.

        For every store config returned by :func:`get_stores`, the path is
        resolved (empty paths fall back to the legacy default), and a
        :class:`LinkStore` is created. Stores are keyed by name, so two stores
        that happen to resolve to the same path remain distinct entries.
        """
        self._stores: Dict[str, LinkStore] = {}
        for store_cfg in get_stores():
            name = store_cfg["name"]
            path = store_cfg["path"]
            resolved_path = path if path else get_links_file_path()
            self._stores[name] = LinkStore(
                filepath=resolved_path, shared=store_cfg["shared"]
            )

    def get_store_names(self) -> List[str]:
        """Return the names of all configured stores.

        Returns:
            A list of store names in insertion/config order.
        """
        return list(self._stores.keys())

    def get_store(self, name: str) -> Optional[LinkStore]:
        """Return the :class:`LinkStore` with the given name.

        Args:
            name: The store name to look up.

        Returns:
            The matching :class:`LinkStore`, or ``None`` if no such store exists.
        """
        return self._stores.get(name)

    def get_default_store_name(self) -> str:
        """Return the name of the default store.

        The "Local" store is preferred when present; otherwise the first
        configured store is returned. If no stores are configured, an empty
        string is returned.

        Returns:
            The default store name, or ``""`` when no stores exist.
        """
        if "Local" in self._stores:
            return "Local"
        if self._stores:
            return next(iter(self._stores))
        return ""

    def add_link(self, link: Link, store_name: Optional[str] = None) -> None:
        """Add a link to the given store (or the default store).

        The link's ``store`` attribute is set to the destination store name
        before persisting. A missing id is generated by the underlying store.

        Args:
            link: The :class:`Link` to add.
            store_name: Target store name. If ``None``, the default store is
                used.
        """
        target = store_name or self.get_default_store_name()
        link.store = target
        store = self._stores[target]
        store.add(link)

    def update_link(self, link: Link, store_name: Optional[str] = None) -> None:
        """Update an existing link in its store.

        The store used is *store_name* if provided, otherwise the store named
        in ``link.store``, falling back to the default store.

        Args:
            link: The :class:`Link` with updated fields (must have a valid id).
            store_name: Optional explicit store name overriding ``link.store``.
        """
        target = store_name or link.store or self.get_default_store_name()
        link.store = target
        store = self._stores[target]
        store.update(link)

    def delete_link(self, link_id: str, store_name: str) -> None:
        """Delete a link from a specific store.

        Args:
            link_id: The unique identifier of the link to remove.
            store_name: The name of the store to delete from.
        """
        store = self._stores[store_name]
        store.delete(link_id)

    def bulk_delete(self, link_ids: List[str], store_name: str) -> None:
        """Delete multiple links from a specific store.

        Args:
            link_ids: List of link identifiers to delete.
            store_name: The name of the store to delete from.
        """
        store = self._stores[store_name]
        store.bulk_delete(link_ids)

    def get_all_links(self) -> List[Link]:
        """Aggregate all links across every store.

        Links from each store are concatenated in store-name order and tagged
        with their owning store name via the ``store`` attribute.

        Returns:
            A combined list of all links from all stores.
        """
        result: List[Link] = []
        for name in self.get_store_names():
            for link in self._stores[name].get_all():
                link.store = name
                result.append(link)
        return result

    def find_link(self, link_id: str) -> Tuple[Optional[Link], Optional[str]]:
        """Find a link by id across all stores.

        Args:
            link_id: The unique identifier of the link to find.

        Returns:
            A tuple of ``(link, store_name)``. The link's ``store`` attribute
            is set to its owning store. ``(None, None)`` if not found.
        """
        for name in self.get_store_names():
            for link in self._stores[name].get_all():
                if link.id == link_id:
                    link.store = name
                    return link, name
        return None, None

    def find_store_of_link(self, link_id: str) -> Optional[str]:
        """Return the name of the store that contains the given link.

        Args:
            link_id: The unique identifier of the link to locate.

        Returns:
            The owning store name, or ``None`` if the link is not found.
        """
        _, store_name = self.find_link(link_id)
        return store_name

    def search(self, query: str) -> List[Link]:
        """Search for links across all stores.

        Results from each store are concatenated in store-name order and each
        link's ``store`` attribute is set to its owning store.

        Args:
            query: The search term (empty returns all links from all stores).

        Returns:
            A combined list of matching links.
        """
        result: List[Link] = []
        for name in self.get_store_names():
            for link in self._stores[name].search(query):
                link.store = name
                result.append(link)
        return result

    def update_last_accessed(self, link_id: str) -> None:
        """Update the ``last_accessed`` timestamp for a link.

        The link's owning store is located automatically.

        Args:
            link_id: The unique identifier of the link to touch.
        """
        store_name = self.find_store_of_link(link_id)
        if store_name is not None:
            self._stores[store_name].update_last_accessed(link_id)

    def _local_store(self) -> LinkStore:
        """Return the store that owns local-only recent-exclusion data.

        The non-shared "Local" store is preferred; if it does not exist the
        default store is used instead.

        Returns:
            The :class:`LinkStore` responsible for excluded recent URLs.
        """
        local = self._stores.get("Local")
        if local is not None and not local.shared:
            return local
        default_name = self.get_default_store_name()
        return self._stores[default_name]

    def get_excluded_recent_urls(self) -> set[str]:
        """Return the set of excluded recent/favorite URLs (local only).

        Returns:
            The set of excluded URLs from the local store.
        """
        return self._local_store().get_excluded_recent_urls()

    def add_excluded_recent_url(self, url: str) -> None:
        """Add a URL to the local exclusion list for recent/favorite imports.

        Args:
            url: The URL to exclude from recent-item imports.
        """
        self._local_store().add_excluded_recent_url(url)

    def shared_stores(self) -> List[LinkStore]:
        """Return all stores marked as shared.

        Returns:
            A list of shared :class:`LinkStore` instances.
        """
        return [store for store in self._stores.values() if store.shared]
